import { Product, Category, Review, Banner } from "./types";

export const banners: Banner[] = [
  {
    id: "banner-aqua",
    title: "Promo Aqua",
    subtitle: "Promo Aqua Spesial",
    image: "/banners/baner aqua.png",
  },
  {
    id: "banner-kapal-api",
    title: "Promo Kapal Api",
    subtitle: "Promo Kapal Api Spesial",
    image: "/banners/baner kapal api.png",
  },
  {
    id: "banner-mie",
    title: "Promo Mie",
    subtitle: "Promo Mie Spesial",
    image: "/banners/baner mie.png",
  },
];

export const categories: Category[] = [
  { id: "all", name: "Semua", icon: "LayoutGrid" },
  { id: "snack", name: "Snack", icon: "Cookie" },
  { id: "minuman", name: "Minuman", icon: "Coffee" },
  { id: "kebutuhan", name: "Kebutuhan Pokok", icon: "ShoppingBasket" },
  { id: "atk", name: "Alat Tulis", icon: "Pencil" },
  { id: "kebersihan", name: "Kebersihan", icon: "Sparkles" },
];

export const products: Product[] = [
  // SNACK PRODUCTS
  {
    id: "s1",
    slug: "chitato-sapi-gulung",
    name: "Chitato Beef Barbeque 68g",
    price: 15000,
    originalPrice: 18000,
    category: "snack",
    rating: 4.8,
    reviewCount: 234,
    sold: 1250,
    stock: 99,
    description:
      "Chitato rasa Beef Barbeque kemasan 68g. Keripik kentang premium dengan rasa yang lezat.",
    variants: [
      { id: "v1", name: "Original", stock: 50 },
      { id: "v2", name: "Beef Barbeque", stock: 0 },
      { id: "v3", name: "Spicy", stock: 15 },
    ],
  },
  {
    id: "s2",
    slug: "taro-snack-net-68g",
    name: "Taro Snack Net 68g",
    price: 12000,
    originalPrice: 14500,
    category: "snack",
    rating: 4.7,
    reviewCount: 189,
    sold: 980,
    stock: 99,
    description:
      "Taro snack jaring-jaring rasa keju dan rumput laut. Renyah dan gurih.",
  },
  {
    id: "s3",
    slug: "oreo-sandwich-133g",
    name: "Oreo Sandwich 133g",
    price: 18000,
    originalPrice: 21000,
    category: "snack",
    rating: 4.9,
    reviewCount: 312,
    sold: 2150,
    stock: 99,
    description:
      "Biskuit Oreo dengan krim vanilla. Kemasan 133g, cocok untuk camilan.",
  },
  {
    id: "s4",
    slug: "pocky-chocolate-40g",
    name: "Pocky Chocolate 40g",
    price: 12000,
    originalPrice: 15000,
    category: "snack",
    rating: 4.6,
    reviewCount: 167,
    sold: 876,
    stock: 99,
    description: "Stik biskuit dengan lapisan coklat premium. Kemasan 40g.",
  },
  {
    id: "s5",
    slug: "momogi-10-pcs",
    name: "Momogi 10 Pcs",
    price: 10000,
    originalPrice: 12000,
    category: "snack",
    rating: 4.5,
    reviewCount: 145,
    sold: 2340,
    stock: 99,
    description: "Snack jagung rasa keju. Kemasan isi 10 pcs.",
  },

  // MINUMAN PRODUCTS
  {
    id: "m1",
    slug: "aqua-600ml-12-pcs",
    name: "Aqua 600ml (12 pcs)",
    price: 45000,
    originalPrice: 50000,
    category: "minuman",
    rating: 4.8,
    reviewCount: 456,
    sold: 3450,
    stock: 99,
    description: "Air mineral Aqua kemasan 600ml. Satu dus isi 12 botol.",
  },
  {
    id: "m2",
    slug: "teh-botol-sosro-350ml",
    name: "Teh Botol Sosro 350ml",
    price: 5000,
    originalPrice: 6000,
    category: "minuman",
    rating: 4.7,
    reviewCount: 389,
    sold: 2876,
    stock: 99,
    description:
      "Teh botol Sosro kemasan 350ml. Teh asli dengan rasa yang segar.",
  },
  {
    id: "m3",
    slug: "fanta-strawberry-250ml",
    name: "Fanta Strawberry 250ml",
    price: 7000,
    originalPrice: 8000,
    category: "minuman",
    rating: 4.6,
    reviewCount: 234,
    sold: 1654,
    stock: 99,
    description: "Minuman ringan rasa stroberi. Kemasan 250ml.",
  },
  {
    id: "m4",
    slug: "coca-cola-320ml",
    name: "Coca-Cola 320ml",
    price: 7000,
    originalPrice: 8000,
    category: "minuman",
    rating: 4.8,
    reviewCount: 567,
    sold: 4321,
    stock: 99,
    description: "Minuman ringan Coca-Cola kemasan 320ml. Segar dan nikmat.",
  },
  {
    id: "m5",
    slug: "pocari-sweat-500ml",
    name: "Pocari Sweat 500ml",
    price: 10000,
    originalPrice: 12000,
    category: "minuman",
    rating: 4.9,
    reviewCount: 278,
    sold: 1987,
    stock: 99,
    description:
      "Minuman isotonik Pocari Sweat kemasan 500ml. Mengembalikan cairan tubuh.",
  },

  // KEBUTUHAN POKOK
  {
    id: "k1",
    slug: "beras-rojolele-5kg",
    name: "Beras Rojolele 5kg",
    price: 65000,
    originalPrice: 70000,
    category: "kebutuhan",
    rating: 4.9,
    reviewCount: 567,
    sold: 3456,
    stock: 99,
    description: "Beras Rojolele premium 5kg. Pulen dan berkualitas.",
  },
  {
    id: "k2",
    slug: "minyak-goreng-bimoli-2l",
    name: "Minyak Goreng Bimoli 2L",
    price: 45000,
    originalPrice: 50000,
    category: "kebutuhan",
    rating: 4.8,
    reviewCount: 432,
    sold: 2876,
    stock: 99,
    description:
      "Minyak goreng Bimoli kemasan 2 liter. Berkualitas dan menyehatkan.",
  },
  {
    id: "k3",
    slug: "gula-pasir-1kg",
    name: "Gula Pasir 1kg",
    price: 18000,
    originalPrice: 20000,
    category: "kebutuhan",
    rating: 4.7,
    reviewCount: 345,
    sold: 2345,
    stock: 99,
    description: "Gula pasir putih berkualitas. Kemasan 1kg.",
  },
  {
    id: "k4",
    slug: "telur-ayam-10pcs",
    name: "Telur Ayam 10 pcs",
    price: 25000,
    originalPrice: 28000,
    category: "kebutuhan",
    rating: 4.8,
    reviewCount: 398,
    sold: 3210,
    stock: 99,
    description: "Telur ayam negeri segar. Isi 10 butir.",
  },
  {
    id: "k5",
    slug: "mie-instan-indomie-1dus",
    name: "Indomie Goreng 1 dus (40 pcs)",
    price: 120000,
    originalPrice: 130000,
    category: "kebutuhan",
    rating: 4.9,
    reviewCount: 678,
    sold: 4567,
    stock: 99,
    description: "Indomie goreng 1 dus isi 40 bungkus. Praktis dan lezat.",
  },

  // ALAT TULIS
  {
    id: "a1",
    slug: "pulpen-standard-12pcs",
    name: "Pulpen Standard (12 pcs)",
    price: 30000,
    originalPrice: 36000,
    category: "atk",
    rating: 4.6,
    reviewCount: 234,
    sold: 1876,
    stock: 99,
    description: "Pulpen hitam isi 12 pcs. Tinta hitam, nyaman digunakan.",
  },
  {
    id: "a2",
    slug: "buku-tulis-58-lembar",
    name: "Buku Tulis 58 Lembar",
    price: 5000,
    originalPrice: 6000,
    category: "atk",
    rating: 4.7,
    reviewCount: 389,
    sold: 3210,
    stock: 99,
    description:
      "Buku tulis 58 lembar. Kertas berkualitas, tidak mudah tembus.",
  },
  {
    id: "a3",
    slug: "penghapus-pencil",
    name: "Penghapus Pencil",
    price: 3000,
    originalPrice: 4000,
    category: "atk",
    rating: 4.5,
    reviewCount: 167,
    sold: 2345,
    stock: 99,
    description: "Penghapus pensil putih. Lembut dan tidak merusak kertas.",
  },
  {
    id: "a4",
    slug: "penggaris-30cm",
    name: "Penggaris 30cm",
    price: 5000,
    originalPrice: 6000,
    category: "atk",
    rating: 4.6,
    reviewCount: 145,
    sold: 1654,
    stock: 99,
    description:
      "Penggaris plastik bening panjang 30cm. Akurat dan tidak mudah patah.",
  },
  {
    id: "a5",
    slug: "spidol-whiteboard-set",
    name: "Spidol Whiteboard Set (4 warna)",
    price: 25000,
    originalPrice: 30000,
    category: "atk",
    rating: 4.7,
    reviewCount: 198,
    sold: 987,
    stock: 99,
    description:
      "Set spidol whiteboard 4 warna (hitam, merah, biru, hijau). Bisa dihapus.",
  },

  // KEBERSIHAN
  {
    id: "c1",
    slug: "sabun-cuci-piring-sunlight",
    name: "Sabun Cuci Piring Sunlight 400ml",
    price: 15000,
    originalPrice: 18000,
    category: "kebersihan",
    rating: 4.8,
    reviewCount: 456,
    sold: 3456,
    stock: 99,
    description:
      "Sabun cuci piring Sunlight lemon 400ml. Ampuh membersihkan lemak.",
  },
  {
    id: "c2",
    slug: "detergen-bubuk-rinso-800g",
    name: "Detergen Bubuk Rinso 800g",
    price: 18000,
    originalPrice: 22000,
    category: "kebersihan",
    rating: 4.9,
    reviewCount: 567,
    sold: 4321,
    stock: 99,
    description:
      "Detergen bubuk Rinso anti noda kemasan 800g. Wangi tahan lama.",
  },
  {
    id: "c3",
    slug: "sabun-mandi-lifebuoy-4pcs",
    name: "Sabun Mandi Lifebuoy (4 pcs)",
    price: 20000,
    originalPrice: 25000,
    category: "kebersihan",
    rating: 4.7,
    reviewCount: 345,
    sold: 2987,
    stock: 99,
    description:
      "Sabun mandi Lifebuoy total protection 4 pcs. Melindungi dari kuman.",
  },
  {
    id: "c4",
    slug: "pembersih-lantai-500ml",
    name: "Pembersih Lantai 500ml",
    price: 15000,
    originalPrice: 18000,
    category: "kebersihan",
    rating: 4.6,
    reviewCount: 234,
    sold: 1876,
    stock: 99,
    description:
      "Pembersih lantai wangi bunga kemasan 500ml. Membuat lantai bersih dan wangi.",
  },
  {
    id: "c5",
    slug: "pelembut-pakaian-molto-500ml",
    name: "Pelembut Pakaian Molto 500ml",
    price: 25000,
    originalPrice: 30000,
    category: "kebersihan",
    rating: 4.8,
    reviewCount: 389,
    sold: 2345,
    stock: 99,
    description: "Pelembut pakaian Molto wangi tahan lama kemasan 500ml.",
  },
];

function generateReviewDate(hoursAgo: number): string {
  const d = new Date();
  d.setHours(d.getHours() - hoursAgo);
  return d.toISOString();
}

export const defaultReviews: Review[] = [
  {
    id: "r1",
    productId: "all",
    name: "Ahmad",
    rating: 5,
    comment: "Proses cepat, admin ramah",
    createdAt: generateReviewDate(1),
    isVerified: true,
    likes: 24,
    dislikes: 1,
  },
  {
    id: "r2",
    productId: "all",
    name: "Rizky",
    rating: 5,
    comment: "Langsung masuk, aman banget",
    createdAt: generateReviewDate(3),
    isVerified: true,
    likes: 12,
    dislikes: 0,
  },
  {
    id: "r3",
    productId: "all",
    name: "Dewi",
    rating: 4,
    comment: "Harga murah, worth it",
    createdAt: generateReviewDate(24),
    isVerified: true,
  },
  {
    id: "r4",
    productId: "all",
    name: "Budi",
    rating: 5,
    comment: "Udah langganan di sini",
    createdAt: generateReviewDate(48),
    isVerified: true,
  },
  {
    id: "r5",
    productId: "all",
    name: "Sari",
    rating: 4,
    comment: "Pelayanan oke, respon cepat",
    createdAt: generateReviewDate(72),
    isVerified: true,
  },
  {
    id: "r6",
    productId: "all",
    name: "Fikri",
    rating: 5,
    comment: "Mantap, produk berkualitas",
    createdAt: generateReviewDate(96),
    isVerified: true,
  },
  {
    id: "r7",
    productId: "all",
    name: "Naina",
    rating: 5,
    comment: "Recommended seller!",
    createdAt: generateReviewDate(120),
    isVerified: true,
  },
  {
    id: "r8",
    productId: "all",
    name: "Dimas",
    rating: 4,
    comment: "Proses lumayan cepat",
    createdAt: generateReviewDate(144),
    isVerified: true,
  },
  {
    id: "r9",
    productId: "all",
    name: "Putri",
    rating: 5,
    comment: "Sudah beli berkali-kali, selalu lancar",
    createdAt: generateReviewDate(168),
    isVerified: true,
  },
  {
    id: "r10",
    productId: "all",
    name: "Wahyu",
    rating: 5,
    comment: "Belanja kebutuhan rumah paling murah di sini",
    createdAt: generateReviewDate(192),
    isVerified: true,
  },
  {
    id: "r11",
    productId: "all",
    name: "Rina",
    rating: 4,
    comment: "Harga bersaing, proses oke",
    createdAt: generateReviewDate(240),
    isVerified: true,
  },
  {
    id: "r12",
    productId: "all",
    name: "Andi",
    rating: 5,
    comment: "Fast response, admin helpful banget",
    createdAt: generateReviewDate(288),
    isVerified: true,
  },
  {
    id: "r13",
    productId: "all",
    name: "Maya",
    rating: 5,
    comment: "Produk sesuai deskripsi, top!",
    createdAt: generateReviewDate(336),
    isVerified: true,
  },
  {
    id: "r14",
    productId: "all",
    name: "Fajar",
    rating: 4,
    comment: "Pengiriman cepat, barang aman",
    createdAt: generateReviewDate(384),
    isVerified: true,
  },
  {
    id: "r15",
    productId: "all",
    name: "Lestari",
    rating: 5,
    comment: "Paling trusted, ga pernah gagal",
    createdAt: generateReviewDate(432),
    isVerified: true,
  },
];
