import { Product, Category, Review, Banner, Order, Notification } from "./types";

export const banners: Banner[] = [
  {
    id: "banner-aqua",
    title: "Promo Aqua",
    subtitle: "Promo Aqua Spesial",
    image: "/banners/baner 1.png",
  },
  {
    id: "banner-kapal-api",
    title: "Promo Kapal Api",
    subtitle: "Promo Kapal Api Spesial",
    image: "/banners/baner 2.png",
  },
  {
    id: "banner-mie",
    title: "Promo Mie",
    subtitle: "Promo Mie Spesial",
    image: "/banners/baner 3.png",
  },
];

export const categories: Category[] = [
  { id: "all", name: "Semua", icon: "LayoutGrid" },
  { id: "pulsa", name: "Pulsa", icon: "Phone", priority: 1 },
  { id: "paket-data", name: "Paket Data", icon: "Wifi", priority: 2 },
  { id: "e-wallet", name: "E-Wallet", icon: "CreditCard", priority: 3 },
  { id: "voucher", name: "Voucher", icon: "Gift", priority: 4 },
  { id: "listrik", name: "Listrik", icon: "Zap", priority: 5 },
  { id: "hiburan", name: "Hiburan", icon: "Tv", priority: 6 },
  { id: "game", name: "Game", icon: "Gamepad2", priority: 7 },
  { id: "produktivitas", name: "Produktivitas", icon: "Briefcase", priority: 8 },
];

export const products: Product[] = [
  // ============ PULSA ============
  {
    id: "p1",
    slug: "telkomsel-pulsa",
    name: "Telkomsel Pulsa",
    price: 5000,
    originalPrice: 5000,
    category: "pulsa",
    rating: 4.9,
    reviewCount: 1234,
    sold: 5432,
    stock: 99,
    description: "Pulsa Telkomsel Rp5.000. Langsung masuk, aman terjamin.",
  },
  {
    id: "p2",
    slug: "indosat-pulsa",
    name: "Indosat Pulsa",
    price: 10000,
    originalPrice: 10000,
    category: "pulsa",
    rating: 4.8,
    reviewCount: 987,
    sold: 4321,
    stock: 99,
    description: "Pulsa Indosat Rp10.000. Proses cepat & aman.",
  },
  {
    id: "p3",
    slug: "axis-pulsa",
    name: "Axis Pulsa",
    price: 19000,
    originalPrice: 20000,
    category: "pulsa",
    rating: 4.7,
    reviewCount: 654,
    sold: 3210,
    stock: 99,
    description: "Pulsa Axis Rp20.000. Langsung aktif.",
  },

  // ============ PAKET DATA ============
  {
    id: "d1",
    slug: "telkomsel-paket-data",
    name: "Telkomsel Paket Data",
    price: 42000,
    originalPrice: 45000,
    category: "paket-data",
    rating: 4.9,
    reviewCount: 2345,
    sold: 8765,
    stock: 99,
    description: "Paket data Telkomsel 3GB masa aktif 30 hari.",
    variant: "3 GB\n30 Hari",
    variants: [
      { id: "v1", name: "1 GB 30 hari", stock: 99 },
      { id: "v2", name: "3 GB 30 hari", stock: 99 },
      { id: "v3", name: "5 GB 30 hari", stock: 99 },
    ],
  },
  {
    id: "d2",
    slug: "indosat-paket-data",
    name: "Indosat Paket Data",
    price: 65000,
    originalPrice: 65000,
    category: "paket-data",
    rating: 4.8,
    reviewCount: 1876,
    sold: 6543,
    stock: 99,
    description: "Paket data Indosat 5GB masa aktif 30 hari. Super cepat.",
    variant: "5 GB\n30 Hari",
    variants: [
      { id: "v1", name: "3 GB 30 hari", stock: 99 },
      { id: "v2", name: "5 GB 30 hari", stock: 99 },
      { id: "v3", name: "10 GB 30 hari", stock: 99 },
    ],
  },
  {
    id: "d3",
    slug: "tri-paket-data",
    name: "Tri Paket Data",
    price: 46000,
    originalPrice: 49000,
    category: "paket-data",
    rating: 4.9,
    reviewCount: 2156,
    sold: 7654,
    stock: 99,
    description: "Paket data Tri 8GB masa aktif 30 hari. Paling murah.",
    variant: "8 GB\n30 Hari",
  },

  // ============ LISTRIK ============
  {
    id: "l1",
    slug: "pln-token-20rb",
    name: "PLN Token Listrik",
    price: 20000,
    originalPrice: 20000,
    category: "listrik",
    rating: 4.9,
    reviewCount: 3456,
    sold: 12345,
    stock: 99,
    description: "Token PLN Rp20.000. Langsung bisa dipakai.",
  },
  {
    id: "l2",
    slug: "pln-token-50rb",
    name: "PLN Token Listrik",
    price: 49000,
    originalPrice: 50000,
    category: "listrik",
    rating: 4.9,
    reviewCount: 2987,
    sold: 10654,
    stock: 99,
    description: "Token PLN Rp50.000. Hemat & terpercaya.",
  },
  {
    id: "l3",
    slug: "pln-token-100rb",
    name: "PLN Token Listrik",
    price: 100000,
    originalPrice: 100000,
    category: "listrik",
    rating: 4.8,
    reviewCount: 2345,
    sold: 8765,
    stock: 99,
    description: "Token PLN Rp100.000. Untuk kebutuhan lebih banyak.",
  },

  // ============ E-WALLET ============
  {
    id: "w1",
    slug: "gopay",
    name: "GoPay",
    price: 50000,
    originalPrice: 50000,
    category: "e-wallet",
    rating: 4.9,
    reviewCount: 4567,
    sold: 15432,
    stock: 99,
    description: "Top up GoPay Rp50.000. Langsung masuk saldo.",
  },
  {
    id: "w2",
    slug: "ovo",
    name: "OVO",
    price: 98000,
    originalPrice: 100000,
    category: "e-wallet",
    rating: 4.9,
    reviewCount: 3876,
    sold: 13210,
    stock: 99,
    description: "Top up OVO Rp100.000. Aman & cepat.",
  },
  {
    id: "w3",
    slug: "dana",
    name: "DANA",
    price: 73000,
    originalPrice: 75000,
    category: "e-wallet",
    rating: 4.8,
    reviewCount: 2987,
    sold: 10543,
    stock: 99,
    description: "Top up DANA Rp75.000. Instant & terpercaya.",
  },

  // ============ PRODUKTIVITAS ============
  {
    id: "b1",
    slug: "microsoft-365",
    name: "Microsoft 365 Personal",
    price: 150000,
    originalPrice: 150000,
    category: "produktivitas",
    rating: 4.9,
    reviewCount: 2876,
    sold: 8765,
    stock: 99,
    description: "Lisensi Microsoft 365 Personal 1 Bulan. Resmi dan terpercaya.",
  },
  {
    id: "b2",
    slug: "zoom-pro",
    name: "Zoom Pro",
    price: 98000,
    originalPrice: 100000,
    category: "produktivitas",
    rating: 4.8,
    reviewCount: 1987,
    sold: 6543,
    stock: 99,
    description: "Lisensi Zoom Pro 1 Bulan. Tanpa batas waktu meeting.",
  },
  {
    id: "b3",
    slug: "google-one",
    name: "Google One 100GB",
    price: 100000,
    originalPrice: 100000,
    category: "produktivitas",
    rating: 4.9,
    reviewCount: 3456,
    sold: 11234,
    stock: 99,
    description: "Langganan Google One 100GB 1 Bulan. Penyimpanan aman.",
  },

  // ============ GAME ============
  {
    id: "g1",
    slug: "mobile-legends-diamonds",
    name: "Mobile Legends Diamonds",
    price: 8000,
    originalPrice: 8000,
    category: "game",
    rating: 4.9,
    reviewCount: 5432,
    sold: 21345,
    stock: 99,
    description: "Top up Mobile Legends 50 Diamond. Langsung masuk game.",
  },
  {
    id: "g2",
    slug: "free-fire-diamonds",
    name: "Free Fire Diamonds",
    price: 11000,
    originalPrice: 12000,
    category: "game",
    rating: 4.9,
    reviewCount: 4876,
    sold: 18765,
    stock: 99,
    description: "Top up Free Fire 100 Diamond. Instant & aman.",
  },
  {
    id: "g3",
    slug: "pubg-uc",
    name: "PUBG Mobile UC",
    price: 39000,
    originalPrice: 42000,
    category: "game",
    rating: 4.8,
    reviewCount: 3210,
    sold: 12345,
    stock: 99,
    description: "Top up PUBG Mobile 300 UC. Cepat & terpercaya.",
  },

  // ============ VOUCHER ============
  {
    id: "vc1",
    slug: "mcdonalds-voucher",
    name: "McDonald's Voucher",
    price: 45000,
    originalPrice: 50000,
    category: "voucher",
    rating: 4.9,
    reviewCount: 3456,
    sold: 12345,
    stock: 99,
    description: "Voucher McDonald's Rp50.000. Hemat & praktis.",
  },
  {
    id: "vc2",
    slug: "kfc-voucher",
    name: "KFC Voucher",
    price: 90000,
    originalPrice: 100000,
    category: "voucher",
    rating: 4.9,
    reviewCount: 2987,
    sold: 10543,
    stock: 99,
    description: "Voucher KFC Rp100.000. Diskon hingga 10%.",
  },
  {
    id: "vc3",
    slug: "gojek-voucher",
    name: "Gojek Food Voucher",
    price: 75000,
    originalPrice: 75000,
    category: "voucher",
    rating: 4.8,
    reviewCount: 2345,
    sold: 8765,
    stock: 99,
    description: "Voucher Gojek Food Rp75.000. Untuk pesan makanan.",
  },

  // ============ HIBURAN ============
  {
    id: "s1",
    slug: "netflix-premium",
    name: "Netflix Premium",
    price: 120000,
    originalPrice: 120000,
    category: "hiburan",
    rating: 4.9,
    reviewCount: 3876,
    sold: 13210,
    stock: 99,
    description: "Langganan Netflix Premium 1 bulan. 4K Ultra HD & unlimited.",
  },
  {
    id: "s2",
    slug: "spotify-premium",
    name: "Spotify Premium",
    price: 94000,
    originalPrice: 99000,
    category: "hiburan",
    rating: 4.9,
    reviewCount: 2987,
    sold: 10543,
    stock: 99,
    description: "Langganan Spotify Premium 3 bulan. Musik unlimited ad-free.",
  },
  {
    id: "s3",
    slug: "youtube-premium",
    name: "YouTube Premium",
    price: 49000,
    originalPrice: 49000,
    category: "hiburan",
    rating: 4.8,
    reviewCount: 2345,
    sold: 8765,
    stock: 99,
    description: "Langganan YouTube Premium 1 bulan. No ads & offline.",
  },
];

// Reviews remain the same
function generateReviewDate(hoursAgo: number): string {
  const d = new Date();
  d.setHours(d.getHours() - hoursAgo);
  return d.toISOString();
}

export const defaultReviews: Review[] = [
  {
    id: "r1",
    productId: "all",
    name: "Pengguna",
    rating: 5,
    comment: "Proses cepat, admin ramah",
    createdAt: generateReviewDate(1),
    isVerified: true,
    likes: 24,
    dislikes: 1,
    reply: {
      adminName: "Atheris",
      comment:
        "Terima kasih atas ulasan positifnya kak. Ditunggu orderan selanjutnya ya!",
      createdAt: generateReviewDate(0.5),
    },
  },
  {
    id: "r2",
    productId: "all",
    name: "Rizky",
    rating: 5,
    comment: "Langsung masuk, aman banget",
    createdAt: generateReviewDate(3),
    isVerified: true,
    likes: 12,
    dislikes: 0,
    reply: {
      adminName: "Sarah",
      comment:
        "Senang bisa melayani kakak, terima kasih atas kepercayaannya belanja di toko kami.",
      createdAt: generateReviewDate(2),
    },
  },
  {
    id: "r3",
    productId: "all",
    name: "Dewi",
    rating: 4,
    comment: "Harga murah, worth it",
    createdAt: generateReviewDate(24),
    isVerified: true,
  },
  {
    id: "r4",
    productId: "all",
    name: "Budi",
    rating: 5,
    comment: "Udah langganan di sini",
    createdAt: generateReviewDate(48),
    isVerified: true,
  },
  {
    id: "r5",
    productId: "all",
    name: "Sari",
    rating: 4,
    comment: "Pelayanan oke, respon cepat",
    createdAt: generateReviewDate(72),
    isVerified: true,
  },
];

export const mockOrders: Order[] = [
  {
    id: "1",
    orderId: "ORD-2026-001",
    createdAt: "2026-05-11T10:30:00Z",
    status: "completed",
    items: [
      {
        productId: "p1",
        name: "Telkomsel Pulsa",
        category: "pulsa",
        image: null,
        price: 5000,
        quantity: 1,
      },
    ],
    total: 5000,
    paymentMethod: "GoPay",
    customerName: "Ahmad Fauzi",
    phone: "081234567890",
    address: "-",
  },
  {
    id: "2",
    orderId: "ORD-2026-002",
    createdAt: "2026-05-11T08:10:00Z",
    status: "processing",
    items: [
      {
        productId: "d1",
        name: "Telkomsel Paket Data",
        category: "paket-data",
        image: null,
        price: 42000,
        quantity: 1,
      },
    ],
    total: 42000,
    paymentMethod: "OVO",
    customerName: "Ahmad Fauzi",
    phone: "081234567890",
    address: "-",
  },
  {
    id: "3",
    orderId: "ORD-2026-003",
    createdAt: "2026-05-08T14:15:00Z",
    status: "processing",
    items: [
      {
        productId: "l1",
        name: "PLN Token Listrik",
        category: "listrik",
        image: null,
        price: 20000,
        quantity: 1,
      },
      {
        productId: "w1",
        name: "GoPay",
        category: "e-wallet",
        image: null,
        price: 50000,
        quantity: 1,
      },
    ],
    total: 70000,
    paymentMethod: "DANA",
    customerName: "Ahmad Fauzi",
    phone: "081234567890",
    address: "-",
  },
  {
    id: "4",
    orderId: "ORD-2026-004",
    createdAt: "2026-05-05T19:40:00Z",
    status: "completed",
    items: [
      {
        productId: "g1",
        name: "Mobile Legends Diamonds",
        category: "game",
        image: null,
        price: 8000,
        quantity: 1,
      },
    ],
    total: 8000,
    paymentMethod: "ShopeePay",
    customerName: "Ahmad Fauzi",
    phone: "081234567890",
    address: "-",
  },
  {
    id: "5",
    orderId: "ORD-2026-005",
    createdAt: "2026-05-03T11:00:00Z",
    status: "cancelled",
    items: [
      {
        productId: "vc1",
        name: "McDonald's Voucher",
        category: "voucher",
        image: null,
        price: 45000,
        quantity: 1,
      },
    ],
    total: 45000,
    paymentMethod: "BCA VA",
    customerName: "Ahmad Fauzi",
    phone: "081234567890",
    address: "-",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    type: "activity",
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    activityTitle: "Pesanan berhasil dibuat",
    productName: "Telkomsel Pulsa",
    orderId: "ORD-2026-010",
  },
  {
    id: "n2",
    type: "promo",
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    promoProduct: "Mobile Legends Diamonds",
    promoDiscount: 20,
    promoCopy: "Diskon top up diamond hari ini!",
  },
  {
    id: "n3",
    type: "activity",
    isRead: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    activityTitle: "Pesanan berhasil dibuat",
    productName: "Netflix Premium",
    orderId: "ORD-2026-009",
  },
  {
    id: "n4",
    type: "promo",
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    promoProduct: "PLN Token Listrik",
    promoDiscount: 15,
    promoCopy: "Promo token listrik hemat untukmu!",
  },
  {
    id: "n5",
    type: "activity",
    isRead: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    activityTitle: "Pesanan berhasil dibuat",
    productName: "GoPay",
    orderId: "ORD-2026-007",
  },
];

export const mockFavorites: Product[] = products.filter(p => ["p1", "d1", "l1", "g1", "s1"].includes(p.id));
