import { Product, Category, Review, Banner } from "./types";

export const banners: Banner[] = [
  {
    id: "banner-aqua",
    title: "Promo Aqua",
    subtitle: "Promo Aqua Spesial",
    image: "/banners/baner 1.png",
  },
  {
    id: "banner-kapal-api",
    title: "Promo Kapal Api",
    subtitle: "Promo Kapal Api Spesial",
    image: "/banners/baner 2.png",
  },
  {
    id: "banner-mie",
    title: "Promo Mie",
    subtitle: "Promo Mie Spesial",
    image: "/banners/baner 3.png",
  },
];

export const categories: Category[] = [
  { id: "all", name: "Semua", icon: "LayoutGrid" },
  { id: "pulsa", name: "Pulsa", icon: "Phone", priority: 1 },
  { id: "paket-data", name: "Paket Data", icon: "Wifi", priority: 2 },
  { id: "e-wallet", name: "E-Wallet", icon: "CreditCard", priority: 3 },
  { id: "voucher", name: "Voucher", icon: "Gift", priority: 4 },
  { id: "listrik", name: "Listrik", icon: "Zap", priority: 5 },
  { id: "tagihan", name: "Tagihan", icon: "FileText", priority: 6 },
  { id: "game", name: "Game", icon: "Gamepad2", priority: 7 },
  { id: "subscription", name: "Subscription", icon: "Star", priority: 8 },
];

export const products: Product[] = [
  // ============ PULSA ============
  {
    id: "p1",
    slug: "telkomsel-pulsa-5000",
    name: "Telkomsel Pulsa 5.000",
    price: 5000,
    originalPrice: 5000,
    category: "pulsa",
    rating: 4.9,
    reviewCount: 1234,
    sold: 5432,
    stock: 99,
    description: "Pulsa Telkomsel Rp 5.000. Langsung masuk, aman terjamin.",
    images: [
      "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==",
    ],
  },
  {
    id: "p2",
    slug: "indosat-pulsa-10000",
    name: "Indosat Pulsa 10.000",
    price: 10000,
    originalPrice: 10000,
    category: "pulsa",
    rating: 4.8,
    reviewCount: 987,
    sold: 4321,
    stock: 99,
    description: "Pulsa Indosat Rp 10.000. Proses cepat & aman.",
  },
  {
    id: "p3",
    slug: "axis-pulsa-20000",
    name: "Axis Pulsa 20.000",
    price: 20000,
    originalPrice: 20000,
    category: "pulsa",
    rating: 4.7,
    reviewCount: 654,
    sold: 3210,
    stock: 99,
    description: "Pulsa Axis Rp 20.000. Langsung aktif.",
  },
  {
    id: "p4",
    slug: "smartfren-pulsa-15000",
    name: "Smartfren Pulsa 15.000",
    price: 15000,
    originalPrice: 15000,
    category: "pulsa",
    rating: 4.6,
    reviewCount: 543,
    sold: 2876,
    stock: 99,
    description: "Pulsa Smartfren Rp 15.000. Harga kompetitif.",
  },
  {
    id: "p5",
    slug: "tri-pulsa-25000",
    name: "Tri Pulsa 25.000",
    price: 25000,
    originalPrice: 25000,
    category: "pulsa",
    rating: 4.8,
    reviewCount: 789,
    sold: 3654,
    stock: 99,
    description: "Pulsa Tri Rp 25.000. Cepat & terpercaya.",
  },

  // ============ PAKET DATA ============
  {
    id: "d1",
    slug: "telkomsel-data-3gb",
    name: "Telkomsel Data",
    price: 45000,
    originalPrice: 45000,
    category: "paket-data",
    rating: 4.9,
    reviewCount: 2345,
    sold: 8765,
    stock: 99,
    description: "Paket data Telkomsel masa aktif 30 hari. Unlimited apps.",
    variant: "1 GB\n30 Hari",
    variants: [
      { id: "v1", name: "1 Gb 30 hari", stock: 99 },
      { id: "v2", name: "3 Gb 30 hari", stock: 99 },
      { id: "v3", name: "5 Gb 30 hari", stock: 99 },
    ],
  },
  {
    id: "d2",
    slug: "indosat-data-5gb",
    name: "Indosat Data",
    price: 65000,
    originalPrice: 65000,
    category: "paket-data",
    rating: 4.8,
    reviewCount: 1876,
    sold: 6543,
    stock: 99,
    description: "Paket data Indosat masa aktif 30 hari. Super cepat.",
    variant: "5 GB\n30 Hari",
    variants: [
      { id: "v1", name: "3 Gb 30 hari", stock: 99 },
      { id: "v2", name: "5 Gb 30 hari", stock: 99 },
      { id: "v3", name: "10 Gb 30 hari", stock: 99 },
    ],
  },
  {
    id: "d3",
    slug: "axis-data-6gb",
    name: "Axis Data",
    price: 55000,
    originalPrice: 55000,
    category: "paket-data",
    rating: 4.7,
    reviewCount: 1543,
    sold: 5432,
    stock: 99,
    description: "Paket data Axis 6GB masa aktif 30 hari. Irit & cepat.",
    variant: "6 GB\n30 Hari",
  },
  {
    id: "d4",
    slug: "tri-data-8gb",
    name: "Tri Data",
    price: 49000,
    originalPrice: 49000,
    category: "paket-data",
    rating: 4.9,
    reviewCount: 2156,
    sold: 7654,
    stock: 99,
    description: "Paket data Tri 8GB masa aktif 30 hari. Paling murah.",
    variant: "8 GB\n30 Hari",
  },
  {
    id: "d5",
    slug: "smartfren-data-10gb",
    name: "Smartfren Data",
    price: 39000,
    originalPrice: 39000,
    category: "paket-data",
    rating: 4.6,
    reviewCount: 987,
    sold: 4321,
    stock: 99,
    description: "Paket data Smartfren 10GB masa aktif 30 hari. Ultra hemat.",
    variant: "10 GB\n30 Hari",
  },

  // ============ LISTRIK ============
  {
    id: "l1",
    slug: "pln-token-20000",
    name: "PLN Token 20.000",
    price: 20000,
    originalPrice: 20000,
    category: "listrik",
    rating: 4.9,
    reviewCount: 3456,
    sold: 12345,
    stock: 99,
    description: "Token PLN Rp 20.000. Langsung bisa dipakai.",
  },
  {
    id: "l2",
    slug: "pln-token-50000",
    name: "PLN Token 50.000",
    price: 50000,
    originalPrice: 50000,
    category: "listrik",
    rating: 4.9,
    reviewCount: 2987,
    sold: 10654,
    stock: 99,
    description: "Token PLN Rp 50.000. Hemat & terpercaya.",
  },
  {
    id: "l3",
    slug: "pln-token-100000",
    name: "PLN Token 100.000",
    price: 100000,
    originalPrice: 100000,
    category: "listrik",
    rating: 4.8,
    reviewCount: 2345,
    sold: 8765,
    stock: 99,
    description: "Token PLN Rp 100.000. Untuk kebutuhan lebih banyak.",
  },
  {
    id: "l4",
    slug: "pln-token-200000",
    name: "PLN Token 200.000",
    price: 200000,
    originalPrice: 200000,
    category: "listrik",
    rating: 4.8,
    reviewCount: 1654,
    sold: 5432,
    stock: 99,
    description: "Token PLN Rp 200.000. Untuk penggunaan jangka panjang.",
  },
  {
    id: "l5",
    slug: "pln-token-300000",
    name: "PLN Token 300.000",
    price: 300000,
    originalPrice: 300000,
    category: "listrik",
    rating: 4.7,
    reviewCount: 1234,
    sold: 3876,
    stock: 99,
    description: "Token PLN Rp 300.000. Paket hemat keluarga.",
  },

  // ============ E-WALLET ============
  {
    id: "w1",
    slug: "gopay-top-up-50000",
    name: "GoPay Top Up 50.000",
    price: 50000,
    originalPrice: 50000,
    category: "e-wallet",
    rating: 4.9,
    reviewCount: 4567,
    sold: 15432,
    stock: 99,
    description: "Top up GoPay Rp 50.000. Langsung masuk saldo.",
  },
  {
    id: "w2",
    slug: "ovo-top-up-100000",
    name: "OVO Top Up 100.000",
    price: 100000,
    originalPrice: 100000,
    category: "e-wallet",
    rating: 4.9,
    reviewCount: 3876,
    sold: 13210,
    stock: 99,
    description: "Top up OVO Rp 100.000. Aman & cepat.",
  },
  {
    id: "w3",
    slug: "dana-top-up-75000",
    name: "DANA Top Up 75.000",
    price: 75000,
    originalPrice: 75000,
    category: "e-wallet",
    rating: 4.8,
    reviewCount: 2987,
    sold: 10543,
    stock: 99,
    description: "Top up DANA Rp 75.000. Instant & terpercaya.",
  },
  {
    id: "w4",
    slug: "linkaja-top-up-50000",
    name: "LinkAja Top Up 50.000",
    price: 50000,
    originalPrice: 50000,
    category: "e-wallet",
    rating: 4.7,
    reviewCount: 1876,
    sold: 6543,
    stock: 99,
    description: "Top up LinkAja Rp 50.000. Praktis & hemat.",
  },
  {
    id: "w5",
    slug: "shopeepay-top-up-100000",
    name: "ShopeePay Top Up 100.000",
    price: 100000,
    originalPrice: 100000,
    category: "e-wallet",
    rating: 4.9,
    reviewCount: 3456,
    sold: 12345,
    stock: 99,
    description: "Top up ShopeePay Rp 100.000. Cepat masuk.",
  },

  // ============ TAGIHAN ============
  {
    id: "b1",
    slug: "pln-postpaid-150000",
    name: "PLN Postpaid 150.000",
    price: 150000,
    originalPrice: 150000,
    category: "tagihan",
    rating: 4.9,
    reviewCount: 2876,
    sold: 8765,
    stock: 99,
    description: "Pembayaran tagihan PLN Rp 150.000. Aman tersertifikasi.",
  },
  {
    id: "b2",
    slug: "pam-tagihan-100000",
    name: "PAM Tagihan 100.000",
    price: 100000,
    originalPrice: 100000,
    category: "tagihan",
    rating: 4.8,
    reviewCount: 1987,
    sold: 6543,
    stock: 99,
    description: "Pembayaran tagihan PDAM Rp 100.000. Langsung verifikasi.",
  },
  {
    id: "b3",
    slug: "internet-telkom-300000",
    name: "Internet Telkom 300.000",
    price: 300000,
    originalPrice: 300000,
    category: "tagihan",
    rating: 4.8,
    reviewCount: 1654,
    sold: 5432,
    stock: 99,
    description: "Pembayaran tagihan internet Rp 300.000. Terpercaya.",
  },
  {
    id: "b4",
    slug: "bpjs-kesehatan-100000",
    name: "BPJS Kesehatan 100.000",
    price: 100000,
    originalPrice: 100000,
    category: "tagihan",
    rating: 4.9,
    reviewCount: 3456,
    sold: 11234,
    stock: 99,
    description: "Pembayaran BPJS Kesehatan Rp 100.000. Sistem resmi.",
  },
  {
    id: "b5",
    slug: "cicilan-kartu-kredit-500000",
    name: "Cicilan Kartu Kredit 500.000",
    price: 500000,
    originalPrice: 500000,
    category: "tagihan",
    rating: 4.8,
    reviewCount: 987,
    sold: 3210,
    stock: 99,
    description: "Pembayaran cicilan kartu kredit Rp 500.000.",
  },

  // ============ GAME ============
  {
    id: "g1",
    slug: "mobile-legends-diamonds-50",
    name: "Mobile Legends 50 Diamonds",
    price: 8000,
    originalPrice: 8000,
    category: "game",
    rating: 4.9,
    reviewCount: 5432,
    sold: 21345,
    stock: 99,
    description: "Top up Mobile Legends 50 Diamond. Langsung masuk game.",
  },
  {
    id: "g2",
    slug: "free-fire-diamonds-100",
    name: "Free Fire 100 Diamonds",
    price: 12000,
    originalPrice: 12000,
    category: "game",
    rating: 4.9,
    reviewCount: 4876,
    sold: 18765,
    stock: 99,
    description: "Top up Free Fire 100 Diamond. Instant & aman.",
  },
  {
    id: "g3",
    slug: "pubg-uc-300",
    name: "PUBG Mobile 300 UC",
    price: 42000,
    originalPrice: 42000,
    category: "game",
    rating: 4.8,
    reviewCount: 3210,
    sold: 12345,
    stock: 99,
    description: "Top up PUBG Mobile 300 UC. Cepat & terpercaya.",
  },
  {
    id: "g4",
    slug: "genshin-impact-1380-crystal",
    name: "Genshin Impact 1380 Crystal",
    price: 169000,
    originalPrice: 169000,
    category: "game",
    rating: 4.8,
    reviewCount: 1987,
    sold: 6543,
    stock: 99,
    description: "Top up Genshin Impact 1380 Crystal. Best rate.",
  },
  {
    id: "g5",
    slug: "honkai-star-rail-300-pass",
    name: "Honkai Star Rail 300 Star Jade",
    price: 39000,
    originalPrice: 39000,
    category: "game",
    rating: 4.7,
    reviewCount: 1654,
    sold: 5432,
    stock: 99,
    description: "Top up Honkai Star Rail 300 Star Jade. Harga kompetitif.",
  },

  // ============ VOUCHER ============
  {
    id: "v1",
    slug: "mcdonalds-voucher-50000",
    name: "McDonald's Voucher 50.000",
    price: 45000,
    originalPrice: 50000,
    category: "voucher",
    rating: 4.9,
    reviewCount: 3456,
    sold: 12345,
    stock: 99,
    description: "Voucher McDonald's Rp 50.000. Hemat & praktis.",
  },
  {
    id: "v2",
    slug: "kfc-voucher-100000",
    name: "KFC Voucher 100.000",
    price: 90000,
    originalPrice: 100000,
    category: "voucher",
    rating: 4.9,
    reviewCount: 2987,
    sold: 10543,
    stock: 99,
    description: "Voucher KFC Rp 100.000. Diskon hingga 10%.",
  },
  {
    id: "v3",
    slug: "gojek-voucher-75000",
    name: "Gojek Food Voucher 75.000",
    price: 70000,
    originalPrice: 75000,
    category: "voucher",
    rating: 4.8,
    reviewCount: 2345,
    sold: 8765,
    stock: 99,
    description: "Voucher Gojek Food Rp 75.000. Untuk pesan makanan.",
  },
  {
    id: "v4",
    slug: "grabfood-voucher-100000",
    name: "GrabFood Voucher 100.000",
    price: 92000,
    originalPrice: 100000,
    category: "voucher",
    rating: 4.8,
    reviewCount: 1876,
    sold: 6543,
    stock: 99,
    description: "Voucher GrabFood Rp 100.000. Belanja hemat.",
  },
  {
    id: "v5",
    slug: "shopee-voucher-100000",
    name: "Shopee Voucher 100.000",
    price: 95000,
    originalPrice: 100000,
    category: "voucher",
    rating: 4.9,
    reviewCount: 4321,
    sold: 15432,
    stock: 99,
    description: "Voucher Shopee Rp 100.000. Belanja lebih hemat.",
  },

  // ============ SUBSCRIPTION ============
  {
    id: "s1",
    slug: "netflix-1-bulan",
    name: "Netflix Premium (1 Bulan)",
    price: 120000,
    originalPrice: 120000,
    category: "subscription",
    rating: 4.9,
    reviewCount: 3876,
    sold: 13210,
    stock: 99,
    description: "Langganan Netflix Premium 1 bulan. 4K Ultra HD & unlimited.",
  },
  {
    id: "s2",
    slug: "spotify-3-bulan",
    name: "Spotify Premium (3 Bulan)",
    price: 99000,
    originalPrice: 99000,
    category: "subscription",
    rating: 4.9,
    reviewCount: 2987,
    sold: 10543,
    stock: 99,
    description: "Langganan Spotify Premium 3 bulan. Musik unlimited ad-free.",
  },
  {
    id: "s3",
    slug: "youtube-premium-1-bulan",
    name: "YouTube Premium (1 Bulan)",
    price: 49000,
    originalPrice: 49000,
    category: "subscription",
    rating: 4.8,
    reviewCount: 2345,
    sold: 8765,
    stock: 99,
    description: "Langganan YouTube Premium 1 bulan. No ads & offline.",
  },
  {
    id: "s4",
    slug: "disney-plus-1-bulan",
    name: "Disney+ Premium (1 Bulan)",
    price: 79000,
    originalPrice: 79000,
    category: "subscription",
    rating: 4.8,
    reviewCount: 1654,
    sold: 5432,
    stock: 99,
    description: "Langganan Disney+ 1 bulan. Film & series terlengkap.",
  },
  {
    id: "s5",
    slug: "canva-pro-1-tahun",
    name: "Canva Pro (1 Tahun)",
    price: 119000,
    originalPrice: 119000,
    category: "subscription",
    rating: 4.9,
    reviewCount: 2876,
    sold: 9876,
    stock: 99,
    description: "Langganan Canva Pro 1 tahun. Design tools unlimited.",
  },
];

function generateReviewDate(hoursAgo: number): string {
  const d = new Date();
  d.setHours(d.getHours() - hoursAgo);
  return d.toISOString();
}

export const defaultReviews: Review[] = [
  {
    id: "r1",
    productId: "all",
    name: "Pengguna",
    rating: 5,
    comment: "Proses cepat, admin ramah",
    createdAt: generateReviewDate(1),
    isVerified: true,
    likes: 24,
    dislikes: 1,
    reply: {
      adminName: "Atheris",
      comment: "Terima kasih atas ulasan positifnya kak. Ditunggu orderan selanjutnya ya!",
      createdAt: generateReviewDate(0.5),
    },
  },
  {
    id: "r2",
    productId: "all",
    name: "Rizky",
    rating: 5,
    comment: "Langsung masuk, aman banget",
    createdAt: generateReviewDate(3),
    isVerified: true,
    likes: 12,
    dislikes: 0,
    reply: {
      adminName: "Sarah",
      comment: "Senang bisa melayani kakak, terima kasih atas kepercayaannya belanja di toko kami.",
      createdAt: generateReviewDate(2),
    },
  },
  {
    id: "r3",
    productId: "all",
    name: "Dewi",
    rating: 4,
    comment: "Harga murah, worth it",
    createdAt: generateReviewDate(24),
    isVerified: true,
  },
  {
    id: "r4",
    productId: "all",
    name: "Budi",
    rating: 5,
    comment: "Udah langganan di sini",
    createdAt: generateReviewDate(48),
    isVerified: true,
  },
  {
    id: "r5",
    productId: "all",
    name: "Sari",
    rating: 4,
    comment: "Pelayanan oke, respon cepat",
    createdAt: generateReviewDate(72),
    isVerified: true,
  },
  {
    id: "r6",
    productId: "all",
    name: "Fikri",
    rating: 5,
    comment: "Mantap, produk berkualitas",
    createdAt: generateReviewDate(96),
    isVerified: true,
  },
  {
    id: "r7",
    productId: "all",
    name: "Naina",
    rating: 5,
    comment: "Recommended seller!",
    createdAt: generateReviewDate(120),
    isVerified: true,
  },
  {
    id: "r8",
    productId: "all",
    name: "Dimas",
    rating: 4,
    comment: "Proses lumayan cepat",
    createdAt: generateReviewDate(144),
    isVerified: true,
  },
  {
    id: "r9",
    productId: "all",
    name: "Putri",
    rating: 5,
    comment: "Sudah beli berkali-kali, selalu lancar",
    createdAt: generateReviewDate(168),
    isVerified: true,
  },
  {
    id: "r10",
    productId: "all",
    name: "Wahyu",
    rating: 5,
    comment: "Belanja kebutuhan rumah paling murah di sini",
    createdAt: generateReviewDate(192),
    isVerified: true,
  },
  {
    id: "r11",
    productId: "all",
    name: "Rina",
    rating: 4,
    comment: "Harga bersaing, proses oke",
    createdAt: generateReviewDate(240),
    isVerified: true,
  },
  {
    id: "r12",
    productId: "all",
    name: "Andi",
    rating: 5,
    comment: "Fast response, admin helpful banget",
    createdAt: generateReviewDate(288),
    isVerified: true,
  },
  {
    id: "r13",
    productId: "all",
    name: "Maya",
    rating: 5,
    comment: "Produk sesuai deskripsi, top!",
    createdAt: generateReviewDate(336),
    isVerified: true,
  },
  {
    id: "r14",
    productId: "all",
    name: "Fajar",
    rating: 4,
    comment: "Pengiriman cepat, barang aman",
    createdAt: generateReviewDate(384),
    isVerified: true,
  },
  {
    id: "r15",
    productId: "all",
    name: "Lestari",
    rating: 5,
    comment: "Paling trusted, ga pernah gagal",
    createdAt: generateReviewDate(432),
    isVerified: true,
  },
];
