import { Seller } from "@/lib/types";

export const MOCK_SELLERS: Seller[] = [
  {
    id: "s1",
    name: "Astro Store",
    avatar: null,
    kabupaten: "Kota Bandung",
    provinsi: "Jawa Barat",
    lastMessage: "Pesanan Anda sedang diproses ya kak.",
    time: "10:30",
    unread: 2,
    isOnline: true,
  },
  {
    id: "s2",
    name: "Tech Gadget",
    avatar: null,
    kabupaten: "Kota Surabaya",
    provinsi: "Jawa Timur",
    lastMessage: "Terima kasih telah berbelanja.",
    time: "Kemarin",
    unread: 0,
    isOnline: false,
  },
  {
    id: "s3",
    name: "Fashion Hub",
    avatar: null,
    kabupaten: "Kota Jakarta Selatan",
    provinsi: "DKI Jakarta",
    lastMessage: "Warna hitam ready kak.",
    time: "Kemarin",
    unread: 0,
    isOnline: true,
  },
  {
    id: "s4",
    name: "Home Living",
    avatar: null,
    kabupaten: "Kabupaten Sleman",
    provinsi: "DI Yogyakarta",
    lastMessage: "Apakah barang ini masih ada?",
    time: "Selasa",
    unread: 0,
    isOnline: false,
  },
  {
    id: "s5",
    name: "Digi World",
    avatar: null,
    kabupaten: "Kota Medan",
    provinsi: "Sumatera Utara",
    lastMessage: "Stok masih ada kak, silakan order.",
    time: "Senin",
    unread: 1,
    isOnline: true,
  },
  {
    id: "s6",
    name: "Kreatif Shop",
    avatar: null,
    kabupaten: "Kota Makassar",
    provinsi: "Sulawesi Selatan",
    lastMessage: "Produk sudah dikirim hari ini.",
    time: "Minggu",
    unread: 0,
    isOnline: false,
  },
];
